const CFG={engadget:"https://www.engadget.com/rss.xml",hn:"https://hn.algolia.com/api/v1/search_by_date?tags=story&numericFilters=num_comments%3E%3D300&hitsPerPage=30",google:"https://9to5google.com/feed/",ars:"https://feeds.arstechnica.com/arstechnica/index",techcrunch:"https://techcrunch.com/feed/",tldr:"https://tldr.tech/api/latest/tech",maxItems:10,model:"@cf/meta/llama-3.3-70b-instruct-fp8-fast",aiTimeoutMs:25000,hnFallbacks:1,sections:["AI","Tech","Gadgets","Security","Business","Policy","Science"],label:{"Engadget":"Engadget","Hacker News":"HN","9to5Google":"9to5Google","TLDR Tech":"TLDR","Ars Technica":"Ars","TechCrunch":"TechCrunch"}};
const REQUIRED=["TELEGRAM_BOT_TOKEN","TELEGRAM_CHAT_ID","WEBHOOK_SECRET"];
function requireEnv(env){const missing=REQUIRED.filter(k=>!env[k]);if(missing.length)throw Error(`missing required configuration: ${missing.join(", ")}`);if(!env.NOLLSNEWS_STATE)throw Error("missing KV binding NOLLSNEWS_STATE")}
function safeEqual(a,b){a=String(a||"");b=String(b||"");if(!a||a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
export default {
 async fetch(req,env,ctx){const u=new URL(req.url);
  if(u.pathname==="/health")return Response.json({ok:true,service:"nollsnews-digest"});
  if(req.method==="POST"&&u.pathname==="/telegram"){requireEnv(env);if(!safeEqual(req.headers.get("x-telegram-bot-api-secret-token"),env.WEBHOOK_SECRET))return new Response("forbidden",{status:403});let up;try{up=await req.json()}catch{return new Response("ok")}const m=up.message;if(m&&String(m.chat?.id)===String(env.TELEGRAM_CHAT_ID)&&/^\/status(?:@\w+)?(?:\s|$)/i.test(m.text||""))ctx.waitUntil(sendText(env,`NollsNews status\nSources: Engadget, HN 300+ discussions, 9to5Google, Ars Technica, TechCrunch, TLDR Tech\nSchedule: 09:00 and 15:00 PT\nPublishing: ${env.ENABLE_POSTS==="true"?"on":"paused"}`).catch(()=>{}));return new Response("ok")}
  if(req.method==="POST"&&u.pathname.startsWith("/admin/")){requireEnv(env);if(!safeEqual(req.headers.get("x-admin-secret"),env.WEBHOOK_SECRET))return new Response("forbidden",{status:403});
   if(u.pathname==="/admin/set-webhook"){await telegram(env,"setWebhook",{url:`${u.origin}/telegram`,secret_token:env.WEBHOOK_SECRET,allowed_updates:["message"],drop_pending_updates:true});return new Response("webhook configured")}
   if(u.pathname==="/admin/webhook-info"){const j=await telegram(env,"getWebhookInfo",{});const r=j.result||{};return Response.json({url:r.url,pending_update_count:r.pending_update_count,last_error_date:r.last_error_date,last_error_message:r.last_error_message,allowed_updates:r.allowed_updates})}
   if(u.pathname==="/admin/preview"){const xs=await collect(env);const {text,used}=await buildDigest(env,xs,"PREVIEW - new format\n\n");if(!used.length)return Response.json({posted:0});await sendText(env,text,{html:true});return Response.json({posted:1,stories:used.length,chars:text.length,text})}
   return new Response("not found",{status:404})}
  return new Response("NollsNews digest bot")},
 async scheduled(event,env,ctx){requireEnv(env);ctx.waitUntil(runSlot(env))}
};
async function runSlot(env){const parts=Object.fromEntries(new Intl.DateTimeFormat("en-US",{timeZone:"America/Los_Angeles",hour12:false,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit"}).formatToParts(new Date()).filter(x=>x.type!=="literal").map(x=>[x.type,x.value]));if(!["09","15"].includes(parts.hour))return;const slot=`${parts.year}-${parts.month}-${parts.day}-${parts.hour}`;if(await env.NOLLSNEWS_STATE.get(`slot:${slot}`))return;await env.NOLLSNEWS_STATE.put(`slot:${slot}`,"started",{expirationTtl:172800});if(env.ENABLE_POSTS!=="true")return;const items=await collect(env);const {text,used,covered}=await buildDigest(env,items,"");if(used.length){await sendText(env,text,{html:true});await markSeen(env,covered)}await env.NOLLSNEWS_STATE.put(`slot:${slot}`,`sent:${used.length}`,{expirationTtl:172800})}
async function collect(env){const settled=await Promise.allSettled([fetchXml(CFG.engadget,"Engadget"),fetchHn(),fetchXml(CFG.google,"9to5Google"),fetchXml(CFG.ars,"Ars Technica"),fetchXml(CFG.techcrunch,"TechCrunch"),fetchTldr()]);let xs=dedupe(settled.flatMap(x=>x.status==="fulfilled"?x.value:[])).sort((a,b)=>b.ts-a.ts);const seen=await loadSeen(env);xs=xs.filter(x=>!seen.has(x.id));xs=interleave(cluster(xs)).slice(0,CFG.maxItems);const budget={hn:CFG.hnFallbacks};await Promise.all(xs.map(x=>enrich(x,budget)));return xs}
function interleave(xs){const g=new Map;for(const x of xs){if(!g.has(x.source))g.set(x.source,[]);g.get(x.source).push(x)}const out=[],qs=[...g.values()];for(let i=0;out.length<xs.length;i++)for(const q of qs)if(q[i])out.push(q[i]);return out}
async function markSeen(env,xs){const seen=await loadSeen(env);xs.forEach(x=>seen.add(x.id));await env.NOLLSNEWS_STATE.put("seen",JSON.stringify([...seen].slice(-1000)))}
async function fetchXml(url,source){const r=await fetch(url,{headers:{"user-agent":"NollsNews/1.0"}});if(!r.ok)throw Error(`${source} ${r.status}`);const xml=await r.text();return [...xml.matchAll(/<(?:item|entry)\b[\s\S]*?<\/(?:item|entry)>/gi)].slice(0,20).map(m=>m[0]).map(b=>{const x=item(source,field(b,"title"),field(b,"link")||b.match(/<link[^>]+href=["']([^"']+)/i)?.[1],field(b,"description")||field(b,"summary")||field(b,"content"),field(b,"pubDate")||field(b,"published")||field(b,"updated"));x.rawContent=b.match(/<content[^>]*>([\s\S]*?)<\/content>/i)?.[1]||"";return x}).filter(x=>x.title&&x.url)}
async function fetchHn(){const r=await fetch(CFG.hn);if(!r.ok)throw Error(`HN ${r.status}`);const j=await r.json();return(j.hits||[]).map(h=>Object.assign(item("Hacker News",h.title,`https://news.ycombinator.com/item?id=${h.objectID}`,`${h.num_comments} comments on Hacker News.`,h.created_at),{hnId:h.objectID}))}
async function fetchTldr(){const r=await fetch(CFG.tldr,{redirect:"follow"});if(!r.ok)throw Error(`TLDR ${r.status}`);const h=await r.text();return[item("TLDR Tech",meta(h,"og:title")||"TLDR Tech latest",r.url,meta(h,"og:description")||"Latest TLDR Tech edition.",new Date().toISOString())]}
async function enrich(x,budget){let text="";try{const r=await fetch(x.url,{headers:{"user-agent":"NollsNews/1.0"}});if(r.ok&&/html/i.test(r.headers.get("content-type")||"")){const pg=await readPage(r);const desc=pg.meta["og:description"]||pg.meta["description"]||pg.meta["twitter:description"]||"";if(desc&&clean(desc).length>x.summary.length)x.summary=clean(desc).slice(0,520);text=pg.text||pg.ldBody}else await r.body?.cancel()}catch{}
 if(clean(text).length<300&&x.hnId&&budget.hn>0){budget.hn--;try{const h=await hnContext(x.hnId);if(h)text+=" Hacker News discussion (reader comments, not the article): "+h}catch{}}x.context=[...new Set([x.summary,clean(x.rawContent||"").slice(0,1500),clean(text).slice(0,1500)].filter(Boolean))].join(" ").slice(0,1400)}
async function readPage(r){const meta={},paras=[];let ld="",cur=null,len=0;await new HTMLRewriter().on("meta",{element(e){const k=(e.getAttribute("property")||e.getAttribute("name")||"").toLowerCase(),c=e.getAttribute("content");if(k&&c&&!(k in meta))meta[k]=c}}).on('script[type="application/ld+json"]',{text(t){if(ld.length<20000)ld+=t.text}}).on("p",{element(e){if(len>=6000)return;cur="";e.onEndTag(()=>{const s=clean(cur||"");cur=null;if(s.length>=60&&len<6000&&!/sign in|subscribe|newsletter|cookie|all rights reserved|©|is a part of|affiliate commission/i.test(s)){paras.push(s);len+=s.length+1}})},text(t){if(cur!==null&&cur.length<3000)cur+=t.text}}).transform(r).arrayBuffer();let ldBody="";try{const j=JSON.parse(ld.trim().startsWith("[")?ld:"["+ld.replace(/}\s*{/g,"},{")+"]");const f=o=>Array.isArray(o)?o.map(f).find(Boolean):o&&typeof o==="object"?(o.articleBody||f(o["@graph"])):"";ldBody=clean(f(j)||"").slice(0,6000)}catch{}return{meta,text:paras.join(" ").slice(0,6000),ldBody}}
async function hnContext(id){const it=await(await fetch(`https://hacker-news.firebaseio.com/v0/item/${encodeURIComponent(id)}.json`)).json();const out=[clean(it?.text||"")];for(const k of(it?.kids||[]).slice(0,2)){const c=await(await fetch(`https://hacker-news.firebaseio.com/v0/item/${k}.json`)).json();if(c&&!c.deleted&&!c.dead)out.push(clean(c.text||"").slice(0,1500))}return out.filter(Boolean).join(" ")}
async function buildDigest(env,xs,prefix){if(!xs.length)return{text:"",used:[],covered:[]};const lines=await writeLines(env,xs).catch(()=>null);xs.forEach((x,i)=>{const l=lines?.get(i+1);x.line=l?.line||fallbackLine(x);x.section=CFG.sections.includes(l?.section)?l.section:guessSection(x)});const dups=xs.filter((x,i)=>lines?.get(i+1)?.dup);let used=xs.filter(x=>!dups.includes(x)),text;for(;;){text=prefix+render(used);if(text.length<=4000||used.length<=1)break;used=used.slice(0,-1)}return{text:text.slice(0,4096),used,covered:[...used,...dups]}}
function render(xs){return CFG.sections.map(s=>{const ys=xs.filter(x=>x.section===s);return ys.length?`<b>${s}</b>\n`+ys.map(x=>`- ${esc(x.line)} (<a href="${esc(x.url)}">${esc(CFG.label[x.source]||x.source)}</a>)`).join("\n"):""}).filter(Boolean).join("\n\n")}
async function writeLines(env,xs){if(!env.AI)return null;const list=xs.map((x,i)=>`[${i+1}] Headline: ${x.title}\nSource: ${x.source}\nText: ${x.context||x.summary}`).join("\n\n");const run=env.AI.run(CFG.model,{messages:[{role:"system",content:`You edit a short, direct tech newsletter posted to Telegram. For each numbered story write one line of at most 14 words that says what happened, punchy like a good X post: plain words, no hype, no emoji, no hashtags, no links, no quotes around it. Use only facts in the story text. For a newsletter edition (TLDR), name its two or three main topics. Put each story in exactly one section from: ${CFG.sections.join(", ")}. If a story reports the same news as an earlier numbered story, add "dup" with that earlier number. Reply with only JSON: {"items":[{"i":1,"section":"AI","line":"..."},{"i":2,"section":"AI","line":"...","dup":1}]}`},{role:"user",content:list}],max_tokens:900,temperature:0.2,response_format:{type:"json_object"}});const out=await Promise.race([run,new Promise((_,rej)=>setTimeout(()=>rej(Error("ai timeout")),CFG.aiTimeoutMs))]);let j=out?.response;if(typeof j==="string"){const m=j.match(/\{[\s\S]*\}/);j=m?JSON.parse(m[0]):null}const arr=Array.isArray(j)?j:j?.items;if(!Array.isArray(arr))return null;const map=new Map;for(const o of arr){const i=Number(o?.i),line=clean(o?.line||"").replace(/^[-*\u2022]\s*/,"").replace(/^"|"$/g,"");if(i>=1&&i<=xs.length&&line.length>=8&&!/https?:\/\//.test(line))map.set(i,{section:String(o.section||"").trim(),line:line.split(/\s+/).slice(0,20).join(" "),dup:Number(o.dup)>=1&&Number(o.dup)<i?Number(o.dup):0})}return map}
function fallbackLine(x){const t=x.title;return t.length>110?t.slice(0,107).replace(/\s+\S*$/,"")+"...":t}
function guessSection(x){const t=`${x.title} ${x.summary}`;return/\b(AI|A\.I\.|OpenAI|Anthropic|Gemini|GPT|LLM|Claude|chatbot|model)\b/i.test(t)?"AI":/\b(hack|breach|malware|ransomware|vulnerab|security)/i.test(t)?"Security":"Tech"}
function esc(s){return String(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
async function sendText(env,text,{html=false,preview=false}={}){const body={chat_id:env.TELEGRAM_CHAT_ID,text:text.slice(0,4096),link_preview_options:{is_disabled:!preview}};if(html)body.parse_mode="HTML";return telegram(env,"sendMessage",body)}
async function telegram(env,method,body){requireEnv(env);const r=await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw Error(`telegram ${method} failed with status ${r.status}`);return r.json()}
function meta(h,k){const e=k.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),m=h.match(new RegExp(`<meta[^>]+(?:property|name)=["']${e}["'][^>]+content=["']([^"']+)["']|<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']${e}["']`,`i`));return clean(m?.[1]||m?.[2]||"")}
function field(s,n){return clean(s.match(new RegExp(`<${n}[^>]*>([\\s\\S]*?)<\\/${n}>`,`i`))?.[1]||"")}
function clean(s){return decode(String(s||"").replace(/<!\[CDATA\[|\]\]>/g,"").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim())}
function decode(s){return String(s||"").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&apos;|&#39;|&#8217;/g,"'").replace(/&nbsp;/g," ")}
function canonical(raw){try{const u=new URL(decode(raw));[...u.searchParams.keys()].forEach(k=>{if(/^utm_|^(gclid|fbclid|mc_cid|mc_eid|ref|source)$/i.test(k))u.searchParams.delete(k)});u.hash="";return u.toString()}catch{return raw||""}}
function item(source,title,url,summary,date){url=canonical(url);return{source,title:clean(title),url,summary:clean(summary).slice(0,520),ts:Date.parse(date)||0,id:url.toLowerCase()}}
function dedupe(xs){const m=new Map;for(const x of xs)if(!m.has(x.id))m.set(x.id,x);return[...m.values()]}
function cluster(xs){const seen=new Set,out=[];for(const x of xs){const k=x.title.toLowerCase().replace(/[^a-z0-9 ]/g,"").split(/\s+/).filter(w=>w.length>4).slice(0,4).sort().join(" ");if(!seen.has(k)){seen.add(k);out.push(x)}}return out}
async function loadSeen(env){try{return new Set(JSON.parse((await env.NOLLSNEWS_STATE.get("seen"))||"[]"))}catch{return new Set}}
