const CFG={verge:"https://www.theverge.com/rss/index.xml",hn:"https://hn.algolia.com/api/v1/search_by_date?tags=story&numericFilters=num_comments%3E%3D300&hitsPerPage=30",cnbc:"https://www.cnbc.com/id/19854910/device/rss/rss.html",tldr:"https://tldr.tech/api/latest/tech",maxItems:8};
const REQUIRED=["TELEGRAM_BOT_TOKEN","TELEGRAM_CHAT_ID","WEBHOOK_SECRET"];
function requireEnv(env){const missing=REQUIRED.filter(k=>!env[k]);if(missing.length)throw Error(`missing required configuration: ${missing.join(", ")}`);if(!env.NOLLSNEWS_STATE)throw Error("missing KV binding NOLLSNEWS_STATE")}
function safeEqual(a,b){a=String(a||"");b=String(b||"");if(!a||a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
export default {
 async fetch(req,env,ctx){const u=new URL(req.url);
  if(u.pathname==="/health")return Response.json({ok:true,service:"nollsnews-digest"});
  if(req.method==="POST"&&u.pathname==="/telegram"){requireEnv(env);if(!safeEqual(req.headers.get("x-telegram-bot-api-secret-token"),env.WEBHOOK_SECRET))return new Response("forbidden",{status:403});let up;try{up=await req.json()}catch{return new Response("ok")}const m=up.message;if(m&&String(m.chat?.id)===String(env.TELEGRAM_CHAT_ID)&&/^\/status(?:@\w+)?(?:\s|$)/i.test(m.text||""))ctx.waitUntil(sendText(env,`NollsNews status\nSources: The Verge, HN 300+, CNBC Tech, TLDR Tech\nSchedule: 09:00 and 15:00 PT\nPublishing: ${env.ENABLE_POSTS==="true"?"on":"paused"}`).catch(()=>{}));return new Response("ok")}
  if(req.method==="POST"&&u.pathname.startsWith("/admin/")){requireEnv(env);if(!safeEqual(req.headers.get("x-admin-secret"),env.WEBHOOK_SECRET))return new Response("forbidden",{status:403});
   if(u.pathname==="/admin/set-webhook"){await telegram(env,"setWebhook",{url:`${u.origin}/telegram`,secret_token:env.WEBHOOK_SECRET,allowed_updates:["message"],drop_pending_updates:true});return new Response("webhook configured")}
   if(u.pathname==="/admin/webhook-info"){const j=await telegram(env,"getWebhookInfo",{});const r=j.result||{};return Response.json({url:r.url,pending_update_count:r.pending_update_count,last_error_date:r.last_error_date,last_error_message:r.last_error_message,allowed_updates:r.allowed_updates})}
   if(u.pathname==="/admin/preview"){const xs=await collect(env,true);const pick=[xs.find(x=>x.image),xs.find(x=>!x.image&&x.source!=="TLDR Tech")||xs.find(x=>!x.image)].filter(Boolean);for(const x of pick)await sendStory(env,x,"PREVIEW - new format\n\n");return Response.json({posted:pick.length,stories:pick.map(x=>({source:x.source,title:x.title,photo:!!x.image}))})}
   return new Response("not found",{status:404})}
  return new Response("NollsNews digest bot")},
 async scheduled(event,env,ctx){requireEnv(env);ctx.waitUntil(runSlot(env))}
};
async function runSlot(env){const parts=Object.fromEntries(new Intl.DateTimeFormat("en-US",{timeZone:"America/Los_Angeles",hour12:false,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit"}).formatToParts(new Date()).filter(x=>x.type!=="literal").map(x=>[x.type,x.value]));if(!["09","15"].includes(parts.hour))return;const slot=`${parts.year}-${parts.month}-${parts.day}-${parts.hour}`;if(await env.NOLLSNEWS_STATE.get(`slot:${slot}`))return;await env.NOLLSNEWS_STATE.put(`slot:${slot}`,"started",{expirationTtl:172800});if(env.ENABLE_POSTS!=="true")return;const items=await collect(env,false);for(const x of items)await sendStory(env,x);await env.NOLLSNEWS_STATE.put(`slot:${slot}`,`sent:${items.length}`,{expirationTtl:172800})}
async function collect(env,preview){const settled=await Promise.allSettled([fetchXml(CFG.verge,"The Verge"),fetchHn(),fetchXml(CFG.cnbc,"CNBC Tech"),fetchTldr()]);let xs=dedupe(settled.flatMap(x=>x.status==="fulfilled"?x.value:[])).sort((a,b)=>b.ts-a.ts);const seen=await loadSeen(env);xs=xs.filter(x=>!seen.has(x.id));xs=cluster(xs).slice(0,CFG.maxItems);await Promise.all(xs.map(enrich));if(!preview){xs.forEach(x=>seen.add(x.id));await env.NOLLSNEWS_STATE.put("seen",JSON.stringify([...seen].slice(-1000)))}return xs}
async function fetchXml(url,source){const r=await fetch(url,{headers:{"user-agent":"NollsNews/1.0"}});if(!r.ok)throw Error(`${source} ${r.status}`);const xml=await r.text();return [...xml.matchAll(/<(?:item|entry)\b[\s\S]*?<\/(?:item|entry)>/gi)].slice(0,20).map(m=>m[0]).map(b=>item(source,field(b,"title"),field(b,"link")||b.match(/<link[^>]+href=["']([^"']+)/i)?.[1],field(b,"description")||field(b,"summary")||field(b,"content"),field(b,"pubDate")||field(b,"published")||field(b,"updated"))).filter(x=>x.title&&x.url)}
async function fetchHn(){const r=await fetch(CFG.hn);if(!r.ok)throw Error(`HN ${r.status}`);const j=await r.json();return(j.hits||[]).map(h=>item("Hacker News",h.title,h.url||`https://news.ycombinator.com/item?id=${h.objectID}`,`${h.num_comments} comments on Hacker News.`,h.created_at))}
async function fetchTldr(){const r=await fetch(CFG.tldr,{redirect:"follow"});if(!r.ok)throw Error(`TLDR ${r.status}`);const h=await r.text();return[item("TLDR Tech",meta(h,"og:title")||"TLDR Tech latest",r.url,meta(h,"og:description")||"Latest TLDR Tech edition.",new Date().toISOString())]}
async function enrich(x){try{const r=await fetch(x.url,{headers:{"user-agent":"NollsNews/1.0"}});if(!r.ok)return;const h=await r.text();const desc=meta(h,"og:description")||meta(h,"description");if(desc&&desc.length>x.summary.length)x.summary=clean(desc).slice(0,520);let image=decode(meta(h,"og:image")||meta(h,"twitter:image"));if(image&&/^https:\/\//.test(image)&&!isDecorative(image,x.source)){const ir=await fetch(image,{method:"HEAD",redirect:"follow"});if(ir.ok&&(ir.headers.get("content-type")||"").startsWith("image/"))x.image=ir.url}}catch{}}
function isDecorative(u,source){return source==="TLDR Tech"&&/logo/i.test(u)}
async function sendStory(env,x,prefix=""){const text=prefix+formatPost(x);if(x.image){try{await telegram(env,"sendPhoto",{chat_id:env.TELEGRAM_CHAT_ID,photo:x.image,caption:text,parse_mode:"HTML"});return}catch{}}await sendText(env,text,{html:true,preview:x.source!=="TLDR Tech"})}
function formatPost(x){const why=whyItMatters(x),norm=t=>t.toLowerCase().replace(/[^a-z0-9]/g,"");return `<b>${esc(x.title.slice(0,300))}</b>\n${why&&!norm(why).startsWith(norm(x.title))?esc(why)+"\n":""}<a href="${esc(x.url)}">${esc(x.source)}</a>`}
function whyItMatters(x){let s=clean(x.summary);const m=s.match(/^(.{25,}?[.!?])(?=\s+[A-Z0-9"'(]|$)/);if(m)s=m[1];if(s.length>220)s=s.slice(0,217).replace(/\s+\S*$/,"")+"...";return s}
function esc(s){return String(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
async function sendText(env,text,{html=false,preview=false}={}){const body={chat_id:env.TELEGRAM_CHAT_ID,text:text.slice(0,4096),link_preview_options:{is_disabled:!preview}};if(html)body.parse_mode="HTML";return telegram(env,"sendMessage",body)}
async function telegram(env,method,body){requireEnv(env);const r=await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/${method}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw Error(`telegram ${method} failed with status ${r.status}`);return r.json()}
function meta(h,k){const e=k.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),m=h.match(new RegExp(`<meta[^>]+(?:property|name)=["']${e}["'][^>]+content=["']([^"']+)["']|<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']${e}["']`,`i`));return clean(m?.[1]||m?.[2]||"")}
function field(s,n){return clean(s.match(new RegExp(`<${n}[^>]*>([\\s\\S]*?)<\\/${n}>`,`i`))?.[1]||"")}
function clean(s){return decode(String(s||"").replace(/<!\[CDATA\[|\]\]>/g,"").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim())}
function decode(s){return String(s||"").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&apos;|&#39;|&#8217;/g,"'").replace(/&nbsp;/g," ")}
function canonical(raw){try{const u=new URL(decode(raw));[...u.searchParams.keys()].forEach(k=>{if(/^utm_|^(gclid|fbclid|mc_cid|mc_eid|ref|source)$/i.test(k))u.searchParams.delete(k)});u.hash="";return u.toString()}catch{return raw||""}}
function item(source,title,url,summary,date){url=canonical(url);return{source,title:clean(title),url,summary:clean(summary).slice(0,520),ts:Date.parse(date)||0,id:url.toLowerCase()}}
function dedupe(xs){const m=new Map;for(const x of xs)if(!m.has(x.id))m.set(x.id,x);return[...m.values()]}
function cluster(xs){const seen=new Set,out=[];for(const x of xs){const k=x.title.toLowerCase().replace(/[^a-z0-9 ]/g,"").split(/\s+/).filter(w=>w.length>4).slice(0,4).sort().join(" ");if(!seen.has(k)){seen.add(k);out.push(x)}}return out}
async function loadSeen(env){try{return new Set(JSON.parse((await env.NOLLSNEWS_STATE.get("seen"))||"[]"))}catch{return new Set}}
